monthly dx

diff --git a/.github/workflows/monthly dx.yml b/.github/workflows/monthly dx.yml
--- a/.github/workflows/monthly dx.yml
+++ b/.github/workflows/monthly dx.yml
@@ -51,52 +51,45 @@ jobs:
           name: PMDViolations
           compression-level: 0
 
-      - name: Read CSV - Blockers'
-        id: csv
-        uses: juliangruber/read-file-action@v1
-        with:
-          path: ./pmd-all.csv
-
-      - name: Create MD - Blockers'
-        uses: petems/csv-to-md-table-action@master
-        id: csv-table-output-blockers
-        with:
-          csvinput: ${{ steps.csv.outputs.content }}
-
-      - name: Summary Table - Blockers
-        id: md_to_output-all
-        run: |
-          ERROR_COUNT=$(wc -l pmd-all.csv|awk '{print $1}')
-          echo $ERROR_COUNT
-          ERROR_COUNT=$((ERROR_COUNT - 1))
-          echo "BLOCKERS FOUND:" $ERROR_COUNT  # Print to console
-          if [[ $ERROR_COUNT > 0 ]]; then
-            echo "## Blockers" >> $GITHUB_STEP_SUMMARY  
-            echo "${{steps.csv-table-output-blockers.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
-          fi
-
-      # - name: 'Run PMD scan to HTML'
-      #   id: pmd_html
+      # - name: 'Run PMD scan to CSV - Blockers'
+      #   id: pmd_csv_blocks
       #   run: |
-      #     ~/pmd/bin/pmd check --dir . --rulesets config/pmd/ruleset.xml --format html --cache .pmdCache --report-file pmd.html --show-suppressed --no-fail-on-violation --no-fail-on-error --minimum-priority 5 --property linePrefix=L --property linkPrefix=https://github.com/${{github.repository}}/blob/${{github.head_ref}}/
-      #     sed -i 's|<title>PMD</title>||g' pmd.html
-      #     sed -i 's|<table |<table width="100%" |g' pmd.html
+      #     ~/pmd/bin/pmd check --dir . --rulesets config/pmd/ruleset.xml --format csv --report-file pmd-blocks.csv --no-cache --no-progress --no-fail-on-violation --no-fail-on-error --property package=false --property ruleSet=false --property problem=false --property rule=false --minimum-severity 2
 
-      # - name: Step Table
-      #   id: html_to_output
+      # - name: Read CSV - Blockers'
+      #   id: csv
+      #   uses: juliangruber/read-file-action@v1
+      #   with:
+      #     path: ./pmd-blocks.csv
+
+      # - name: Create MD - Blockers'
+      #   uses: petems/csv-to-md-table-action@master
+      #   id: csv-table-output-blockers
+      #   with:
+      #     csvinput: ${{ steps.csv.outputs.content }}
+
+      # - name: Summary Table - Blockers
+      #   id: md_to_output-blocks
       #   run: |
-      #     echo "$(cat pmd.html)" >> $GITHUB_STEP_SUMMARY
+      #     ERROR_COUNT=$(wc -l pmd-blocks.csv|awk '{print $1}')
+      #     echo $ERROR_COUNT
+      #     ERROR_COUNT=$((ERROR_COUNT - 1))
+      #     echo "BLOCKERS FOUND:" $ERROR_COUNT  # Print to console
+      #     if [[ $ERROR_COUNT > 0 ]]; then
+      #       echo "## Blockers" >> $GITHUB_STEP_SUMMARY
+      #       echo "${{steps.csv-table-output-blockers.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
+      #     fi
 
-      - name: Evaluate Errrors
-        id: evaluate_errors
-        run: |
-          ERROR_COUNT=$(wc -l pmd-blockers.csv|awk '{print $1}')
-          echo $ERROR_COUNT
-          ERROR_COUNT=$((ERROR_COUNT - 1))
-          # echo $ERROR_COUNT >> "$GITHUB_OUTPUT"
-          echo "ERRORS FOUND:" $ERROR_COUNT  # Print to console
-          if [[ $ERROR_COUNT > 0 ]]; then
-            ERROR_STRING="$ERROR_COUNT Blocking Violations Detected"
-            echo "::error::$ERROR_STRING"
-            exit 1
-          fi
+      # - name: Evaluate Errrors
+      #   id: evaluate_errors
+      #   run: |
+      #     ERROR_COUNT=$(wc -l pmd-blockers.csv|awk '{print $1}')
+      #     echo $ERROR_COUNT
+      #     ERROR_COUNT=$((ERROR_COUNT - 1))
+      #     # echo $ERROR_COUNT >> "$GITHUB_OUTPUT"
+      #     echo "ERRORS FOUND:" $ERROR_COUNT  # Print to console
+      #     if [[ $ERROR_COUNT > 0 ]]; then
+      #       ERROR_STRING="$ERROR_COUNT Blocking Violations Detected"
+      #       echo "::error::$ERROR_STRING"
+      #       exit 1
+      #     fi
