combine

diff --git a/.github/workflows/pr dx cs.yml b/.github/workflows/pr dx cs.yml
--- a/.github/workflows/pr dx cs.yml
+++ b/.github/workflows/pr dx cs.yml
@@ -15,6 +15,14 @@ env:
   hidden_comment_prefix: <!--dtc-scanner-->
 
 jobs:
+  scan-pmd:
+    permissions:
+      contents: read # for actions/checkout to fetch code
+      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+
+    runs-on: ubuntu-latest
+
   scan-codescan-pull-request:
     # permissions:
     #   contents: read # for actions/checkout to fetch code
@@ -23,10 +31,10 @@ jobs:
 
     runs-on: ubuntu-latest
 
-    # outputs:
-    #   blockers_text: ${{ steps.csv_blockers.outputs.content }}
-    #   blockers_count: ${{ steps.evaluate_violations_blockers.outputs.blockers_count }}
-
+    outputs:
+      #   blockers_text: ${{ steps.csv_blockers.outputs.content }}
+      #   blockers_count: ${{ steps.evaluate_violations_blockers.outputs.blockers_count }}
+      quality_gate_status: ${{ steps.quality_gate_check.outputs.status }}
     steps:
       # Check out the source code
       - name: Checkout source code
@@ -101,3 +109,30 @@ jobs:
         with:
           sarif_file: codescan.sarif
           category: CodeScan
+
+      - name: Quality Gate Check on PR
+        id: quality_gate_check
+        if:
+          github.event_name == 'pull_request'
+          #&& github.base_ref == 'master'
+        env:
+          TOKEN: ${{ secrets.AUTORABIT_CODESCAN_TOKEN }}
+          PR_KEY: ${{github.event.number}}
+          PROJECT_KEY: x2od-PMDWorkflowPlayground
+        run: |
+          qg_status=$(curl -s -u "$TOKEN": "https://gov-va.codescan.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_KEY" | jq -r '.projectStatus.status')
+          echo "QG Script --> Quality Gate status is ${qg_status}"
+          if [ "${qg_status}" != "OK" ]; then
+            echo "QG Script --> Quality gate is not OK - exiting with error"
+            
+          fi
+          echo "status=$qg_status" >> $GITHUB_OUTPUT
+
+  fail-for-scan-blockers:
+    runs-on: ubuntu-latest
+    needs: [scan-pmd, scan-codescan-pull-request]
+    if: always()
+    steps:
+      - name: Check Blocker Count for Exit Code
+        if: ${{ needs.scan-pmd.outputs.blockers_count > 0 }} || needs.scan-scan-codescan-pull-request.outputs.status -ne "OK"
+        run: exit 1
