dx-no-errors (#17)
* comment deletion

* if

* error!

* contents

* dx pr

* deletion

* changed action

* v45

* no whitespace

* real space

* boolean

* with

* separator

* no regex

* no html

* monthly dx

* filename

* elif

* no violations

* no upload if no problem

* gt

* check all

* output

* zero

* no output

* retry

* eval

* outputs

* no exit

* rework

* echo quotes

* quote for format

* if stuff?

* no output

* check if blocked

* no single number for all

* echo vc

* no if

* check if

* no step output

* output line

* no quotes

* oneline

* use equals

* if for all

* csv only for violations

* low level error

* cache work

* pr dx cleanup

* brain hurts

* replace

* skip the change

* severity

* trim monthly

* quotes

* fewer quotes

diff --git a/.github/workflows/pr dx.yml b/.github/workflows/pr dx.yml
--- a/.github/workflows/pr dx.yml
+++ b/.github/workflows/pr dx.yml
@@ -1,14 +1,14 @@
-# Unique name for this workflow
+# This is a main workflow to trigger on pull requests for DX repositories
+
 name: On PR (DX)
 
+# Controls when the workflow will run
 on:
   pull_request:
+    branches:
+      - '**'
     types: [opened, synchronize, reopened]
 
-permissions:
-  contents: read
-
-# Jobs to be executed
 jobs:
   scan-pmd:
     permissions:
@@ -17,16 +17,17 @@ jobs:
       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
 
     runs-on: ubuntu-latest
-    outputs:
-      error_count: ${{ steps.evaluate_errors.outputs.ERROR_COUNT }}
+    #outputs:
+    #blocker_count: ${{ steps.evaluate_violations_blockers.outputs.blocker_count }}
+    #violation_count: ${{ steps.evaluate_violations_all.outputs.violation_count }}
 
     steps:
       # Check out the source code
-      - name: 'Checkout source code'
+      - name: Checkout source code
         uses: actions/checkout@v4
 
       # Install PMD
-      - name: 'Install PMD'
+      - name: Install PMD
         id: pmd
         run: |
           PMD_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | grep '.tag_name' | sed 's:.*/::' | sed 's:",::')
@@ -39,17 +40,37 @@ jobs:
           fi
           rm -f .pmdCache
 
-      - name: Collect changed files
+      # - name: Collect changed files
+      #   env:
+      #     GH_TOKEN: ${{ github.token }}
+      #     BRANCH: ${{ github.head_ref }}
+      #   run: |
+      #     echo "Changed files for this PR:"
+      #     gh pr diff "$BRANCH" --name-only > list.txt
+      #     cat list.txt
+
+      - name: Action to get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v45
+        with:
+          output_renamed_files_as_deleted_and_added: true
+          separator: ','
+          old_new_separator: '\n'
+          old_new_files_separator: '\n'
+
+      - name: Add changed files to changed.txt
+        shell: bash
         env:
-          GH_TOKEN: ${{ github.token }}
-          BRANCH: ${{ github.head_ref }}
+          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
         run: |
-          echo "Changed files for this PR:"
-          gh pr diff "$BRANCH" --name-only > changed.txt
+          IFS=$',' read -a ALL_CHANGED_FILES <<< "${{ steps.changed-files.outputs.all_changed_files }}"
+           for file in "${ALL_CHANGED_FILES[@]}"; do
+             echo $file >> changed.txt
+           done
           cat changed.txt
 
       # Run PMD scan
-      - name: 'Run PMD scan to SARIF'
+      - name: Run PMD scan to SARIF
         id: pmd_sarif
         run: ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/pmd/ruleset.xml --format sarif --report-file pmd-cli-report.sarif --cache .pmdCache --no-progress --no-fail-on-violation --no-fail-on-error --minimum-priority 2
 
@@ -59,54 +80,83 @@ jobs:
           sarif_file: pmd-cli-report.sarif
           category: PMD
 
-      - name: 'Run PMD scan to CSV - Blockers'
-        id: pmd_csv
-        run: |
-          ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/pmd/ruleset.xml --format csv --report-file pmd-blockers.csv --cache .pmdCache --no-progress --no-fail-on-violation --no-fail-on-error --property package=false --property ruleSet=false --property problem=false --property rule=false --minimum-priority 2
-          # --relativize-paths-with ${{vars.SFDX_ROOT_DIRECTORY}}
+      ####################### ALL VIOLATIONS CHECK
 
-      - name: Read CSV - Blockers'
-        id: csv
-        uses: juliangruber/read-file-action@v1
-        with:
-          path: ./pmd-blockers.csv
-
-      - name: Create MD - Blockers'
-        uses: petems/csv-to-md-table-action@master
-        id: csv-table-output-blockers
-        with:
-          csvinput: ${{ steps.csv.outputs.content }}
-
-      - name: Summary Table - Blockers
-        id: md_to_output-all
-        run: |
-          echo "## Blockers" >> $GITHUB_STEP_SUMMARY  
-          echo "${{steps.csv-table-output-blockers.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
-
-      - name: 'Run PMD scan to CSV - All violations'
+      - name: Run PMD scan to CSV - All violations
         id: pmd_csv_all
         run: |
-          ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/pmd/ruleset.xml --format csv --report-file pmd-all.csv --cache .pmdCache --no-progress --no-fail-on-violation --no-fail-on-error --property package=false --property ruleSet=false --property problem=false --property rule=false
+          ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/pmd/ruleset.xml --format csv --report-file pmd-all.csv --no-cache --no-progress --no-fail-on-violation --no-fail-on-error --property package=false --property ruleSet=false --property problem=false --property rule=false
 
+      - name: Evaluate All Violations
+        id: evaluate_violations_all
+        run: |
+          csv_line_count=$(wc -l pmd-all.csv|awk '{print $1}')
+          #echo $csv_line_count
+          violation_count=$((csv_line_count - 1))
+          echo "violation_count=$violation_count" >> $GITHUB_OUTPUT
+          echo "VIOLATIONS FOUND:" $violation_count  # Print to console
+           if [[ $violation_count > 0 ]]; then
+             VIOLATION_STRING="$violation_count Scanning Violations Detected (all severities) in changed files - download CSV to check"
+             echo "::error::$VIOLATION_STRING"
+           elif [[ $violation_count == 0 ]]; then
+             echo "::notice::No Scanning Violations Detected"
+           fi
+
+      - name: Priority to Severity
+        id: priority_to_severity_all
+        run: sed -i 's|"Priority"|"Severity"|g' pmd-all.csv
       - name: Upload all violations file in CSV format
+        if: ${{ steps.evaluate_violations_all.outputs.violation_count > 0 }}
         uses: actions/upload-artifact@v4
         with:
           path: pmd-all.csv
           name: PMDViolations
           compression-level: 0
 
-      - name: Evaluate Errrors
-        id: evaluate_errors
+      ############################# BLOCKERS CHECK
+
+      - name: Run PMD scan to CSV - Blockers
+        id: pmd_csv_blockers
         run: |
-          ERROR_COUNT=$(wc -l pmd-blockers.csv|awk '{print $1}')
-          echo $ERROR_COUNT
-          ERROR_COUNT=$((ERROR_COUNT - 1))
-          # echo $ERROR_COUNT >> "$GITHUB_OUTPUT"
-          echo "ERRORS FOUND:" $ERROR_COUNT  # Print to console
-          if [[ $ERROR_COUNT > 0 ]]; then
-            ERROR_STRING="$ERROR_COUNT Blocking Violations Detected"
-            echo "::error::$ERROR_STRING"
+          ~/pmd/bin/pmd check --file-list changed.txt --rulesets config/pmd/ruleset.xml --format csv --report-file pmd-blockers.csv --cache .pmdCache --no-progress --no-fail-on-violation --no-fail-on-error --property package=false --property ruleSet=false --property problem=false --property rule=false --minimum-priority 2
+          # --relativize-paths-with ${{vars.SFDX_ROOT_DIRECTORY}}
+
+      - name: Priority to Severity
+        id: priority_to_severity_blockers
+        run: sed -i 's|"Priority"|"Severity"|g' pmd-blockers.csv
+
+      - name: Read CSV - Blockers
+        id: csv_blockers
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./pmd-blockers.csv
+
+      - name: Create MD - Blockers
+        uses: petems/csv-to-md-table-action@master
+        id: csv-table-blockers
+        with:
+          csvinput: ${{ steps.csv_blockers.outputs.content }}
+
+      # Check blocker count from CSV
+      # If has blockers, exit 1
+      # If no blockers, still upload the file with all violations
+      - name: Evaluate Blocker Violations
+        id: evaluate_violations_blockers
+        run: |
+          csv_blocker_count=$(wc -l pmd-blockers.csv|awk '{print $1}')
+          blocker_count=$((csv_blocker_count - 1))
+          echo "blocker_count=$blocker_count" >> $GITHUB_OUTPUT
+          echo "BLOCKERS FOUND:" $blocker_count  # Print to console
+          if [[ $blocker_count > 0 ]]; then
+            echo "## Blockers in Changed Files" >> $GITHUB_STEP_SUMMARY
+            echo "${{steps.csv-table-blockers.outputs.markdown-table}}" >> $GITHUB_STEP_SUMMARY
+            BLOCKER_STRING="$blocker_count Blocking Violations Detected"
+            echo "::error::$BLOCKER_STRING"
             exit 1
-          elif [[ $aaa -eq "ccc" ]]; then
+          elif [[ $blocker_count == 0 ]]; then
             echo "::notice::No Blocking Violations Detected"
           fi
+
+      - name: Check Blocker Count for Exit Code
+        if: ${{ steps.evaluate_violations_blockers.outputs.blocker_count > 0 }}
+        run: exit 1
