check if

diff --git a/.github/workflows/pr dx.yml b/.github/workflows/pr dx.yml
--- a/.github/workflows/pr dx.yml
+++ b/.github/workflows/pr dx.yml
@@ -95,13 +95,13 @@ jobs:
           violation_count=$((violation_count - 1))
           echo $violation_count >> "$GITHUB_OUTPUT"
           echo "VIOLATIONS FOUND:" $violation_count  # Print to console
-          if [[ $violation_count > 0 ]]; then
-            VIOLATION_STRING="$violation_count Blocking Violations Detected"
-            echo "::error::$VIOLATION_STRING"
-            exit 1
-          elif [[ $violation_count == 0 ]]; then
-            echo "::notice::No Scanning Violations Detected"
-          fi
+          # if [[ $violation_count > 0 ]]; then
+          #   VIOLATION_STRING="$violation_count Blocking Violations Detected"
+          #   echo "::error::$VIOLATION_STRING"
+          #   exit 1
+          # elif [[ $violation_count == 0 ]]; then
+          #   echo "::notice::No Scanning Violations Detected"
+          # fi
 
       - name: Upload all violations file in CSV format
         #if: ${{ steps.evaluate_violations_all.outputs.violation_count > 0 }}
